clock/urls.py
from django.urls import path
from . import views

app_name = 'clock'

urlpatterns = [
    path('', views.clock, name='clock'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.beranda, name='beranda'),
    path('profil', views.profil, name='profil'),
    path('tentang_saya',views.tentangSaya, name='tentangSaya')
]

jadwal/urls.py
from django.urls import path
from . import views
app_name = 'jadwal'

urlpatterns = [
    path('', views.tampilan, name='tampilan'),
    path('atur/', views.jadwal, name='jadwal'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('detail/<int:detail_id>', views.detail, name='detail'),
]

kegiatan/urls.py
from django.urls import path
from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.tampilan1, name='tampilan1'),
    path('atur_kegiatan/', views.kegiatan, name='kegiatan'),
    path('atur_peserta/<int:index>/', views.peserta, name='peserta'),
    path('delete/<int:delete_id>', views.delete1, name='delete1'),
    path('deletePeserta/<int:delete_id>', views.delete2, name='delete2'),
    path('detail/<int:detail_id>', views.detail1, name='detail1'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('clock/', include('clock.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('kegiatan/', include('kegiatan.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1')
]

clock/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models
from django.contrib.auth.models import User

class Schedule(models.Model):
    matkul = models.CharField(max_length = 100)
    dosen = models.CharField(max_length = 100)
    jumlah_sks = models.PositiveIntegerField(default=1)
    deskripsi_matkul = models.TextField()

    LIST_TAHUN_SEMESTER = {
        ('2020/2021', '2020/2021'),
        ('2021/2022', '2021/2022'),
        ('2022/2023', '2022/2023'),
        ('2023/2024', '2023/2024'),
    }
    tahun_semester = models.CharField(
        max_length=100,
        choices = LIST_TAHUN_SEMESTER,
        default = '2020/2021',
        )
    ruang_kelas = models.CharField(max_length = 100)

class Tugas(models.Model):
    nama_tugas = models.CharField(max_length=100)
    deadline = models.DateField()
    jadwal = models.ForeignKey(Schedule, on_delete=models.CASCADE)

kegiatan/models.py
from django.db import models
from django.contrib.auth.models import User

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length = 100)
    deskripsi_kegiatan = models.TextField()
    tanggal_kegiatan = models.DateField()

    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, null= True)

    def __str__(self):
        return self.nama

story1/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms
from .models import Schedule
# Create your views here.

class Schedule_Form(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = "__all__"
        labels = {
            'matkul' : 'Mata Kuliah',
            'dosen' : 'Dosen Pengajar',
            'jumlah_sks' : 'Jumlah SKS',
            'deskripsi_matkul' : 'Deskripsi Mata Kuliah',
            'tahun_semester': 'Tahun Semester',
            'ruang_kelas' : 'Ruang Kelas',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

kegiatan/forms.py
from django import forms
from .models import Kegiatan, Peserta
# Create your views here.

class Activities_Form(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"
        labels = {
            'nama_kegiatan' : 'Kegiatan',
            'nama_peserta' : 'Nama',
            'deskripsi_kegiatan' : 'Deskripsi Kegiatan',
            'deskripsi_matkul' : 'Deskripsi Mata Kuliah',
            'tanggal_kegiatan': 'Tanggal Kegiatan',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )
class Peserta_Form(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['nama']
        labels = {'nama' : 'Nama Peserta'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

clock/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def clock(request):
    jam = datetime.datetime.now()
    return render(request, 'clock.html', {"jam":jam})

homepage/views.py
from django.shortcuts import render

# Create your views here.
def beranda(request):
    return render(request, 'beranda.html')

def profil(request):
    return render(request, 'profil.html')

def tentangSaya(request):
    return render(request, 'tentangSaya.html')

jadwal/views.py
from django.shortcuts import render, redirect
from .forms import Schedule_Form
from .models import Schedule, Tugas

def tampilan(request):
    schedule = Schedule.objects.all()

    context = {
        'semua_schedule':schedule
    }
    return render(request, 'tampilan.html', context)

def jadwal(request):
    schedule_form = Schedule_Form(request.POST or None)
    if request.method == "POST":
        if schedule_form.is_valid():
            schedule_form.save()

        return redirect('jadwal:tampilan')
    
    context = {
        'schedule_form' : schedule_form
    }
    return render(request, 'jadwal.html', context)

def delete(request, delete_id):
    Schedule.objects.filter(id = delete_id).delete()
    return redirect('jadwal:tampilan')

def detail(request, detail_id):
    jenis = Schedule.objects.get(pk = detail_id)
    semua_tugas = Tugas.objects.filter(jadwal = jenis)
    return render(request, 'detail.html', {'jenis': jenis, 'semua_tugas':semua_tugas})

kegiatan/views.py
from django.shortcuts import render, redirect
from .forms import Activities_Form, Peserta_Form
from .models import Kegiatan, Peserta

# Create your views here.
def tampilan1(request):
    semua_kegiatan = Kegiatan.objects.all()
    context = {
        'semua_kegiatan':semua_kegiatan
    }
    return render(request, 'tampilan1.html', context)

def kegiatan(request):
    activities_form = Activities_Form(request.POST or None)
    if request.method == "POST":
        if activities_form.is_valid():
            activities_form.save()
        return redirect('kegiatan:tampilan1')
    
    context = {
        'activities_form' : activities_form
    }
    return render(request, 'kegiatan.html', context)

def peserta(request, index):
    peserta_form = Peserta_Form(request.POST or None)
    if request.method == "POST":
        if peserta_form.is_valid():
            peserta = Peserta(kegiatan=Kegiatan.objects.get(pk = index), nama=peserta_form.data['nama'])
            peserta.save()
        x = '/kegiatan/detail/' + str(index)
        return redirect(x)
    
    context = {
        'peserta_form' : peserta_form
    }
    return render(request, 'peserta.html', context)

def delete1(request, delete_id):
    Kegiatan.objects.filter(id = delete_id).delete()
    return redirect('kegiatan:tampilan1')

def delete2(request, delete_id):
    p = Peserta.objects.get(pk = delete_id)
    p.delete()
    x = '/kegiatan/detail/' + str(p.kegiatan.id)
    return redirect(x)

def detail1(request, detail_id):
    jenis = Kegiatan.objects.get(pk = detail_id)
    semua_peserta = Peserta.objects.filter(kegiatan = jenis)
    return render(request, 'detail1.html', {'jenis': jenis, 'semua_peserta':semua_peserta})

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

clock/templates/clock.html
<!doctype html>
<html lang="en">
  <head>
       <!-- Required meta tags -->
       <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
       <!-- Bootstrap CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
       integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
       crossorigin="anonymous">
       <title>Waktu</title>
  </head>
  <body>
      <h1> Waktu Sekarang : {{jam}} </h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
    crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
       <!-- Required meta tags -->
       <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
       <!-- Bootstrap CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
       integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
       crossorigin="anonymous">
       <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    {% block content %}
    <!--Isi Page-->
    {% endblock %}

      <!--Footer-->
      <div class="container footer">
        <h5>Kontak:</h5>
        <div class="row" style="padding-bottom:0.5rem;">
          <div class="col  d-flex flex-column align-items-center">
            <a href="mailto:muhammad.luthfi92@ui.ac.id" target="_blank">
            <img style="width: 53px;" src="{% static 'icons/email.png' %}" alt="email"></a>
          </div>
          <div class="col  d-flex flex-column align-items-center">
            <a href="https://www.linkedin.com/in/luthfi-fahlevi/" target="_blank">
            <img style="width: 55px" src="{% static 'icons/linkedin.png' %}" alt="linkedin"></a>
          </div>
          <div class="col  d-flex flex-column align-items-center">
            <a href="https://twitter.com/luthfifahlevi01" target="_blank">
            <img style="width: 59px;" src="{% static 'icons/twitter.png' %}" alt="twitter"></a>
          </div>
          <div class="col  d-flex flex-column align-items-center">
            <a href="https://www.facebook.com/luthfi.fahlevi.96" target="_blank">
            <img style="width: 26px;" src="{% static 'icons/facebook.png' %}" alt="facebook"></a>
          </div>
        </div>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
    crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/beranda.html
<!doctype html>
{% include 'navbar.html'%}
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <title>Beranda Story 3 Luthfi</title>
  </head>
  <body>
      <!--Isi Page-->
      <div class="container" id="isi">
        <div class="row justify-content-md-center">
          <div class="col col-lg-2 d-flex">
            
          </div>
          <div class="col-md-auto">
              <h1 class="ucapan">Selamat Datang!</h1>
              <img class="picBeranda" src="{% static 'gallery/picBeranda.png' %}" alt="Luthfi">
              <h3 class="nama">Muhammad Luthfi Fahlevi</h3>
              <p class="deskripsi1">Mahasiswa Fasilkom Universitas Indonesia</p>
            </div>
          <div class="col col-lg-2 d-flex align-items-center">
            <p class="deskripsi2">Saya seorang yang memiliki minat di Software Engineering. 
                Saya memiliki ambisi yang kuat dan dapat belajar dengan baik dan cepat. 
                Sekarang, saya sedang menempuh Sarjana Prodi Ilmu Komputer.</p>
          </div>
        </div>
      </div>
  </body>
</html>
{% endblock %}
{% include 'base.html'%}

homepage/templates/navbar.html
<!doctype html>
{% load static %}
<html lang="en">
  <head></head>
  <body>

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:navy; color: white;">
        <a class="navbar-brand" href="{% url 'homepage:beranda' %}">Luthfi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" 
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'homepage:profil' %}">Profil</a>
            <a class="nav-item nav-link" href="{% url 'homepage:tentangSaya' %}">Tentang Saya</a>
            <a class="nav-item nav-link" href="{% url 'story1:story1' %}">Story 1</a>
            <a class="nav-item nav-link" target="_blank" href="{% url 'clock:clock' %}">Clock</a>
            <a class="nav-item nav-link" href="{% url 'jadwal:tampilan' %}">Schedule</a>
            <a class="nav-item nav-link" href="{% url 'kegiatan:tampilan1' %}">Activities</a>
          </div>
        </div>
    </nav>
    {% block content %}
    <!--Isi Page-->
    {% endblock %}

homepage/templates/profil.html
<!doctype html>
{% include 'navbar.html'%}
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <title>Profil Luthfi</title>
  </head>
  <body>
    <!--Isi Page-->
    <div class="container" style="justify-content: center;">
        <div class="row">
          <div class="col" style="text-align: right;">
            <img class="picProfil" src="{% static 'gallery/picProfil.png' %}" alt="Luthfi">
          </div>
          <div class="col d-flex flex-column justify-content-center" >
            <h1 >Muhammad <br/> <span style="color:blue;">Luthfi</span> <br/> Fahlevi</h1>
        <table class="tabelDeskripsi">
          <tr>
            <th>Tanggal Lahir</th>
            <td>: 30 Agustus 2001</td>
          </tr>
          <tr>
            <th>Jenis Kelamin</th>
            <td>: Laki-laki</td>
          </tr>
          <tr>
            <th>Program Studi</th>
            <td>: Ilmu Komputer</td>
          </tr>
          <tr>
            <th>Universitas</th>
            <td>: Indonesia</td>
          </tr>
          <tr>
            <th>Minat</th>
            <td>: Software Engineering</td>
          </tr>
          <tr>
            <th>Hobi</th>
            <td>: Programming</td>
          </tr>
          <tr>
            <th>Keahlian</th>
            <td>: Python, HTML</td>
          </tr>
        </table>
          </div>
        </div>
    </div>
  </body>
</html>
{% endblock %}
{% include 'base.html'%}

jadwal/templates/detail.html
<!doctype html>
{% include "navbar.html"%}
<html lang="en">
  <head>
{% block content%}
    <title>Detail {{ jenis.matkul }}</title>
  </head>
  <body>
    <h1 style="text-align: center; margin: 3rem 0;">{{ jenis.matkul }}</h1>
    <!--Table-->
    <div class="container">
    <table style="margin: 3rem 0;" class="table table-hover">
      <tbody>
        <tr>
          <th scope="row">Dosen Pengajar</th>
          <td>{{ jenis.dosen }}</td>
        </tr>
        <tr>
          <th scope="row">Jumlah SKS</th>
          <td>{{ jenis.jumlah_sks }}</td>
        </tr>
        <tr>
          <th scope="row">Deskripsi</th>
          <td>{{ jenis.deskripsi_matkul }}</td>
        </tr>
        <tr>
          <th scope="row">Tahun Semester</th>
          <td>{{ jenis.tahun_semester}}</td>
        </tr>
        <tr>
          <th scope="row">Ruang Kelas</th>
          <td>{{ jenis.ruang_kelas }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="container">
    <h1 style="text-align: center;">Tugas</h1>
    <table style="margin: 3rem 0;" class="table table-hover d-flex justify-content-center">
      <tbody>
        {% for tugas in semua_tugas %}
        <tr>
          <th scope="row">{{tugas.nama_tugas}}</td>
          <td>{{tugas.deadline}}</td>
          <td></td>
          <td><a class="btn btn-danger" href="{% url 'jadwal:delete' tugas.id %}">Hapus</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </body>
</html>
{% endblock %}
{% include "base.html"%}

jadwal/templates/jadwal.html
<!DOCTYPE html>
{% include "navbar.html" %}
{% load crispy_forms_tags %}
<html lang="en">
    {% block content %}
<head>
    <title>Atur Jadwal</title>
</head>
<body>
    <h1 style="margin: 3rem 0; text-align: center;">Make Your Schedule!</h1>
    <div class="container">
        <form method="POST">
            <table>
                {% csrf_token %}
                {{ schedule_form|crispy}}
            </table>
            <div style="margin: 3rem 0;">
            <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>
{% endblock %}
{% include "base.html"%}

jadwal/templates/tampilan.html
<!doctype html>
{% include "navbar.html"%}
<html lang="en">
  <head>
{% block content%}
    <style>
      thead, tbody {
        text-align: center;
      }
      .rapi {
        margin: 3rem 0;
        text-align: center;
      }
    </style>
    <title>My Schedule</title>
  </head>
  <body>
    <!--Table-->
    <h1 class="rapi" >Your Schedule :D</h1>
    <div class="container">
    <table class="table table-hover rapi">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No.</th>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Dosen Pengajar</th>
            <th scope="col">Ruang Kelas</th>
            <th scope="col">Cek Detail</th>
            <th scope="col">Hapus Jadwal</th>
          </tr>
        </thead>
        <tbody>
          {% for jenis in semua_schedule %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{jenis.matkul}}</td>
            <td>{{jenis.dosen}}</td>
            <td>{{jenis.ruang_kelas}}</td>
            <td><a class="btn btn-info" href="{% url 'jadwal:detail' jenis.id %}">Info</a></td>
            <td><a class="btn btn-danger" href="{% url 'jadwal:delete' jenis.id %}">Hapus</a></td>
          </tr>
          {% endfor %}  
        </tbody>
      </table>
      <div class="rapi">
        <a class="btn btn-primary" href="{% url 'jadwal:jadwal' %}">Tambah</a>
      </div>
    </div>
  </body>
</html>
{% endblock %}
{% include "base.html"%}

kegiatan/templates/detail1.html
<!doctype html>
{% include "navbar.html"%}
<html lang="en">
  <head>
{% block content%}
    <style>
      td, th, tr {
        text-align: center;
      }
    </style>
    <title>Detail {{ jenis.nama_kegiatan }}</title>
  </head>
  <body>
    <h1 style="text-align: center; margin: 3rem 0;">{{ jenis.nama_kegiatan }}</h1>
    <!--Table-->
    <div class="container">
      <table style="margin: 3rem 0;" class="table table-hover">
        <tbody>
          <tr>
            <th scope="row">Tanggal Kegiatan</th>
          </tr>
          <tr>
            <td>{{ jenis.tanggal_kegiatan }}</td>
          </tr>
          <br>
          <tr>
            <th scope="row">Deskripsi</th>
          </tr>
          <tr>
            <td>{{ jenis.deskripsi_kegiatan }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  <div class="container">
    <h1 style="text-align: center;">Peserta</h1>
    <table style="margin: 3rem 0;" class="table table-hover d-flex justify-content-center">
      <tbody>
        {% for peserta in semua_peserta %}
        <tr>
          <th>{{peserta.nama}}</td>
          <td><a class="btn btn-danger" href="{% url 'kegiatan:delete2' peserta.id %}">Hapus</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div style="margin: 3rem 0; text-align: center;">
    <a class="btn btn-primary" href="/kegiatan/atur_peserta/{{ jenis.id }}">Tambah</a>
  </div>
  </body>
</html>
{% endblock %}
{% include "base.html"%}

kegiatan/templates/tampilan1.html
<!doctype html>
{% include "navbar.html"%}
<html lang="en">
  <head>
{% block content%}
    <style>
      .rapi {
        margin: 3rem 0;
        text-align: center;
      }
    </style>
    <title>My Activities</title>
  </head>
  <body>
    <h1 class="rapi">My Activities</h1>
    <div class="container">
      <div class="row row-cols-2">
        {% for jenis in semua_kegiatan %}
        <div class="col">
          <div class="jumbotron">
            <h1 class="display-4" style="text-align: center;">{{ jenis.nama_kegiatan }}</h1>
            <p class="lead"></p>
            <hr class="my-4">
            <p class="text-align-center">{{ jenis.tanggal_kegiatan}}</p>
            <a class="btn btn-primary btn-lg" href="{% url 'kegiatan:detail1' jenis.id %}" role="button">Detail</a>
            <a class="btn btn-danger btn-lg" href="{% url 'kegiatan:delete1' jenis.id %}" role="button">Hapus</a>
          </div>
        </div>
        {% endfor %}  
      </div>
    </div>
    <div class="rapi">
      <a class="btn btn-primary" href="{% url 'kegiatan:kegiatan' %}">Tambah</a>
    </div>
  </body>
</html>
{% endblock %}
{% include "base.html"%}

story1/templates/story1.html
<html>
{% load static %}
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'stylestory1.css' %}">
        <title>Profile Luthfi</title>
    </head>
    <body>
        <a href="{% url 'homepage:beranda' %}"><b>Kembali ke Beranda</b></a>
        <center><h1>Profil Saya</h1 sty></center>
        <table class="table1">
            <tr>
                <td>Nama</td>
                <td>: </td>
                <td>Muhammad Luthfi Fahlevi</td>
            </tr>
            <tr>
                <td>NPM</td>
                <td>: </td>
                <td>1906293215</td>
            </tr>
            <tr>
                <td>Angkatan</td>
                <td>: </td>
                <td>2019</td>
           </tr>
            <tr>
                <td>Hobi</td>
                <td>: </td>
                <td>Bulu tangkis</td>
            </tr>
            <tr>
                <td class="td2">Tempat Kuliah</td>
                <td>: </td>
                <td>Universitas Indonesia</td>
            </tr>
            <tr>
                <td>Deskripsi</td>
                <td>: </td>
                <td>Luthfi berasal dari Palangka Raya, Kalimantan Tengah. 
                    Dia lolos jurusan Ilmu Komputer, Fasilkom, 
                    Universitas Indonesia melalui jalur SNMPTN.
                    Dia memulai pengaplikasian penggunaan coding sejak perkuliahan.

                </td>
            </tr>
        </table>
        <br><br>
        <center><img src="{% static 'mypicture.jpg' %}" width="150" height="220" alt="mahasiswa bernama Luthfi"></center>
        <br>
        

        <table style="text-align: center;" id="edit">
            <tr>
                <th>Riwayat Pendidikan</th>
                <th>Sekolah/Universitas</th>
                <th>Tahun</th>
            </tr>
            <tr>
                <td>Sekolah Dasar</td>
                <td>SDN 6 Palangka Raya</td>
                <td>2007-2013</td>
            </tr>
            <tr>
                <td>Sekolah Menengah Pertama</td>
                <td>SMPN 2 Palangka Raya</td>
                <td>2013-2016</td>
            </tr>
            <tr>
                <td>Sekolah Menengah Atas</td>
                <td>SMAN 2 Palangka Raya</td>
                <td>2016-2019</td>
            </tr>
            <tr>
                <td>Universitas</td>
                <td>Universitas Indonesia</td>
                <td>2019-Sekarang</td>
            </tr>
        </table>

        <br>
    <center>
        <a href="https://www.facebook.com/luthfi.fahlevi.96">
            <img src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" style="width:50;height:50;">
        </a>
        <a href="https://twitter.com/luthfifahlevi01">
            <img src="https://www.eventsnewsasia.com/wp-content/uploads/2019/03/Twitter.png" style="width: 50;height: 40;">
        </a>
        <a href="https://www.linkedin.com/in/luthfi-fahlevi/">
            <img src="http://pngimg.com/uploads/linkedIn/linkedIn_PNG38.png" style="width: 60;height: 60;">
        </a>
    </center>
    </body>
</html>